


    

export const PAGE_COMPANY = "MASTER.COMPANY"
export const PAGE_USER = "MASTER.USERS"
export const PAGE_USERROLE = "MASTER.USERROLES"
export const PAGE_USERPAGES = "MASTER.USERPAGES"

export const PAGE_COMMON ="PAGE_COMMON"


