export default 
{
    CREATE : "PERMISSION.CREATE",
    UPDATE : "PERMISSION.UPDATE",
    DELETE : "PERMISSION.DELETE",
    VIEW :   "PERMISSION.VIEW",
    APPROVAL : "PERMISSION.APPROVAL",
    REJECT : "PERMISSION.REJECT",
}